### PR TITLE
Fixed Issue #109

### PR DESCRIPTION
**Pull request by iiEpic**
- Removed ".decode" on line 209 in file crunchyroll.py
- Added " b' " on line 98 in file browser_instance.py

Verified in comments for issue 109

### CODE REVIEW

**Comment by EpicUnknown** [comment]
Hey Xonshiz, On line 92 of browser_instance.py the same b' needs to be added. I forgot to hit that one up on my commit. I saw it tonight and wanted to make sure you knew.

Line 92 should now read:
if b'href=\"/logout\"' in html_source:

**Comment by Xonshiz** [comment]
Thanks for the update. I'll add it on my side and release a binary later tonight.

**Comment by Thedarklife74** [comment]
> Thanks for the update. I'll add it on my side and release a binary later tonight.

Nice have you updated the binary ?

**Comment by Xonshiz** [comment]
Not yet.



Thank You,
Dhruv Kanojia
(Github <https://github.com/Xonshiz>| Website <https://itsxonshiz.in> |
Twitter <https://twitter.com/Xonshiz> | LinkedIn
<https://in.linkedin.com/in/dhruvkanojia> | Google+
<https://plus.google.com/+DhruvKanojia>)

**Comment by iiEpic** [comment]
[test_distro.zip](https://github.com/Xonshiz/anime-dl/files/4043469/test_distro.zip)

@Thedarklife74  Try out this binary with the newest update from Xonshiz. I pulled his newest update into mine and remade the exe. Let me know if it works.

**EDIT: That zip file contains ONLY the exe file. Nothing more.**

**Comment by Thedarklife74** [comment]
> [test_distro.zip](https://github.com/Xonshiz/anime-dl/files/4043469/test_distro.zip)
> 
> @Thedarklife74 Try out this binary with the newest update from Xonshiz. I pulled his newest update into mine and remade the exe. Let me know if it works.
> 
> **EDIT: That zip file contains ONLY the exe file. Nothing more.**

It seems archive is corrupted

**Comment by iiEpic** [comment]
[anime-dl.zip](https://github.com/Xonshiz/anime-dl/files/4043691/anime-dl.zip)
@Thedarklife74  
My apologies. Try this one, the previous one I zipped using my Linux machine and sometimes I've noticed it corrupts stuff.. my bad haha

Also for reference, these two screenshots show it working with the current build
https://gyazo.com/360c86c26dba9c0080ec191d5444cac9
https://gyazo.com/2c8a3de0d5891cc64ae63ebfb7edeae4

**Comment by Thedarklife74** [comment]
> [anime-dl.zip](https://github.com/Xonshiz/anime-dl/files/4043691/anime-dl.zip)
> @Thedarklife74
> My apologies. Try this one, the previous one I zipped using my Linux machine and sometimes I've noticed it corrupts stuff.. my bad haha
> 
> Also for reference, these two screenshots show it working with the current build
> https://gyazo.com/360c86c26dba9c0080ec191d5444cac9
> https://gyazo.com/2c8a3de0d5891cc64ae63ebfb7edeae4

Work perfectly ! Big thanks :)

**Comment by iiEpic** [comment]
Perfect! I'm glad it worked out man.
@Xonshiz 
If you want a binary to add the one above is from the newest source code after you made your #111 commit boss man.

**Comment by Thedarklife74** [comment]
@EpicUnknown  here we go again. I change nothing on my computer : 

Trying to login...
Let me check again...
Unable to Log you in. Check credentials again.
Failed Login!!!
Traceback (most recent call last):
  File "anime_dl\__main__.py", line 22, in <module>
    class Main():
  File "anime_dl\__main__.py", line 82, in Main
    logger=logger, episode_range=args.range, output=args.output)
  File "anime_dl\Anime_dl.py", line 30, in __init__
    skipper=skipper, logger=logger, episode_range=episode_range, output=output)
  File "anime_dl\sites\crunchyroll.py", line 49, in __init__
NameError: name 'exit' is not defined
[1548] Failed to execute script __main__

**Comment by iiEpic** [comment]
What was the command you tried using?

**Comment by Thedarklife74** [comment]
> What was the command you tried using?

same as always : 


anime-dl.exe -i "link" -u "user" -p "pass" -r "720" -v

Before yesterday it work perfectly and yesterday it don't work anymore. My account work on the webiste and he's premium

**Comment by iiEpic** [comment]
Not sure what's going on but let me see the verbose info. Remember to remove any info that is on your account.

**Comment by Thedarklife74** [comment]
> Not sure what's going on but let me see the verbose info. Remember to remove any info that is on your account.


DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['https://www.crunchyroll.com/fr/somali-and-the-forest-spirit/episode-3-the-sea-at-the-bottom-of-the-cave-792595'], language='Japanese', output=None, password=[''], range='All', resolution=['720'], skip=False, username=[''], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.18362
DEBUG: Python Version : 3.7.4 (32bit)
DEBUG: Starting new HTTPS connection (1): www.crunchyroll.com:443
DEBUG: https://www.crunchyroll.com:443 "GET /login HTTP/1.1" 302 None
DEBUG: https://www.crunchyroll.com:443 "GET /fr/login HTTP/1.1" 200 None
DEBUG: https://www.crunchyroll.com:443 "POST /login HTTP/1.1" 302 None
DEBUG: https://www.crunchyroll.com:443 "GET /fr/login HTTP/1.1" 200 None
DEBUG: Starting new HTTPS connection (1): www.crunchyroll.com:443
DEBUG: https://www.crunchyroll.com:443 "GET / HTTP/1.1" 302 None
DEBUG: https://www.crunchyroll.com:443 "GET /fr HTTP/1.1" 200 None

**Comment by iiEpic** [comment]
> 
> 
> > Not sure what's going on but let me see the verbose info. Remember to remove any info that is on your account.
> 
> DEBUG: You have successfully set the Debugging On.
> DEBUG: Arguments Provided : Namespace(input=['https://www.crunchyroll.com/fr/somali-and-the-forest-spirit/episode-3-the-sea-at-the-bottom-of-the-cave-792595'], language='Japanese', output=None, password=[''], range='All', resolution=['720'], skip=False, username=[''], verbose=True, version=False)
> DEBUG: Operating System : Windows - 10 - 10.0.18362
> DEBUG: Python Version : 3.7.4 (32bit)
> DEBUG: Starting new HTTPS connection (1): [www.crunchyroll.com:443](http://www.crunchyroll.com:443)
> DEBUG: https://www.crunchyroll.com:443 "GET /login HTTP/1.1" 302 None
> DEBUG: https://www.crunchyroll.com:443 "GET /fr/login HTTP/1.1" 200 None
> DEBUG: https://www.crunchyroll.com:443 "POST /login HTTP/1.1" 302 None
> DEBUG: https://www.crunchyroll.com:443 "GET /fr/login HTTP/1.1" 200 None
> DEBUG: Starting new HTTPS connection (1): [www.crunchyroll.com:443](http://www.crunchyroll.com:443)
> DEBUG: https://www.crunchyroll.com:443 "GET / HTTP/1.1" 302 None
> DEBUG: https://www.crunchyroll.com:443 "GET /fr HTTP/1.1" 200 None

That so strange. I just ran my anime-dl.exe with the same file you're trying to download and didn't have any problems.. I wonder what's happened in your case. Is it just that episode or all?

**Comment by Thedarklife74** [comment]
> > > Not sure what's going on but let me see the verbose info. Remember to remove any info that is on your account.
> > 
> > 
> > DEBUG: You have successfully set the Debugging On.
> > DEBUG: Arguments Provided : Namespace(input=['https://www.crunchyroll.com/fr/somali-and-the-forest-spirit/episode-3-the-sea-at-the-bottom-of-the-cave-792595'], language='Japanese', output=None, password=[''], range='All', resolution=['720'], skip=False, username=[''], verbose=True, version=False)
> > DEBUG: Operating System : Windows - 10 - 10.0.18362
> > DEBUG: Python Version : 3.7.4 (32bit)
> > DEBUG: Starting new HTTPS connection (1): [www.crunchyroll.com:443](http://www.crunchyroll.com:443)
> > DEBUG: https://www.crunchyroll.com:443 "GET /login HTTP/1.1" 302 None
> > DEBUG: https://www.crunchyroll.com:443 "GET /fr/login HTTP/1.1" 200 None
> > DEBUG: https://www.crunchyroll.com:443 "POST /login HTTP/1.1" 302 None
> > DEBUG: https://www.crunchyroll.com:443 "GET /fr/login HTTP/1.1" 200 None
> > DEBUG: Starting new HTTPS connection (1): [www.crunchyroll.com:443](http://www.crunchyroll.com:443)
> > DEBUG: https://www.crunchyroll.com:443 "GET / HTTP/1.1" 302 None
> > DEBUG: https://www.crunchyroll.com:443 "GET /fr HTTP/1.1" 200 None
> 
> That so strange. I just ran my anime-dl.exe with the same file you're trying to download and didn't have any problems.. I wonder what's happened in your case. Is it just that episode or all?

All,

Anyway for unknow reason it work today ....

**Comment by Thedarklife74** [comment]
@EpicUnknown  doyou trust me if i said yesterday script working and today no ?
I think I'm going to turn crazy

**Comment by iiEpic** [comment]
@Thedarklife74 That's quite interesting.. I'm not understanding how you're having these problems honestly.

The best advice I can give it to delete your 'anime-dl' exe and redownload the one I gave you the other day. Idk what else to suggest at this point.

**Pull request merged**
