### PR TITLE
add support for --language in mkvmerge

### PR DESCRIPTION
**Pull request by Abu3safeer**
P.S: I am not python developer, but I tried my best to not ruit the code.
video players now could recognize the language, it should select the right language according to user preferences.

### CODE REVIEW

**Comment by Abu3safeer** [comment]
Thank you for the merge, could you please update windows binary? 
I want to test it to see if it works properly.

**Comment by Xonshiz** [comment]
Will release later today after I fix a few things.

**Comment by Xonshiz** [comment]
and thanks for the PR :)

**Comment by Abu3safeer** [comment]
Okey, waiting for it.

**Comment by Abu3safeer** [comment]
PR? Sorry I don't know what it means.

**Pull request merged**
